### ISSUE TITLE
Batch assign function for Issues

### ISSUE THREAD

**Issue by lewbager** [jamieshepherd/tygr#17]
Some sort of higher level check box to select and assign many issues to depts/people so PMs don't have to open every issue and assign.

Thanks Bye

**Comment by jamieshepherd** [comment]
Expect that this won't be done in time for beta will push to 1.0.0 release.

**Comment by zenduo** [comment]
Great ideal @lewbager would save a lot of time going through each item.

**Comment by jamieshepherd** [comment]
This is partly done now, but I still want to ideally add assigning issues to this which will be a little more complex, hopefully get it done in the next few days.
