### ISSUE TITLE
Dropdown menus for Project creation

### ISSUE THREAD

**Issue by lewbager** [jamieshepherd/tygr#18]
To simplify and reduce potential for typo issues, you could have dropdown menus for Authoring Tool and LMS specification. 
Also it might be worth having the type of disribution- i.e. iPads, Desktop etc and an area for short notes that can show up on the project page for everyone to see- i.e. 'This will be translated into Greek and Russian' or whatever.

**Comment by jamieshepherd** [comment]
Project notes is a reasonable idea, I dislike dropdown select boxes with the way they are randomly rendered between browsers/OS, and I don't really think it's necessary for this purpose. With text fields they can be as specific as they like, and it's editable so if typos are a thing, they can be fixed easily. PMs will generally spend 5 minutes when creating a project and completing everything as fully as possible. I'll have a think about implementing project notes, going to push for post 1.0.0 release unless I can think of a nice way to approach this before then.
