### ISSUE TITLE
Issues locked on client side once submitted

### ISSUE THREAD

**Issue by lewbager** [jamieshepherd/tygr#19]
Once an issue is entered by the client they can still edit it- this could cause confusion and potentially mean things are missed. Should the client be able to resolve issues that aren't assigned to them? Obviously they need to check stuff off on client review, but surely then the PM will assign the issue to them to close off?

**Comment by jamieshepherd** [comment]
They have to be able to edit issues, in case of mistakes.

Client can resolve any issues (and close them off) - at the end of the day it's going to be the client deciding whether or not something is an issue. For example, a client creates an issue (which automatically assigns it to Sponge UK), then decides it's not a problem, so they can resolve and close it off themselves.

Everything that happens on an issue is logged in the issue history, so this helps anyone being particularly cheeky and going back on themselves for example.
