### ISSUE TITLE
Consolidate pages?

### ISSUE THREAD

**Issue by lewbager** [jamieshepherd/tygr#21]
Is there anything more that needs to go on the project overview page? If not, could the issues be listed on that page, rather than having to click through again to them? This might make the interface a bit slicker as you'd have all the project details on one page.

![image](https://cloud.githubusercontent.com/assets/10811967/6003833/9112b5d8-aaf6-11e4-8fa5-1b357dab41f8.png)

**Comment by jamieshepherd** [comment]
Alan (@zenduo) felt the same about this, but I have left this page "intentionally blank" as I'd like to move towards more project management oriented features once we hit release, for example, communication between clients (a la Basecamp). For now, it can serve as  the base for some quick information about this particular project - such as LMS deployment information, and who the lead employees are.
