### ISSUE TITLE
Login background image

### ISSUE THREAD

**Issue by jamieshepherd** [jamieshepherd/tygr#29]
Get design to create or look at possible background image for login page. There's a high chance MD won't like the unsplash one!

**Comment by zenduo** [comment]
@jamieshepherd agree :+1: Ben would probably do something nice why not give him a shout.

**Comment by jamieshepherd** [comment]
Ben is going to take a look at designing something for this.

**Comment by jamieshepherd** [comment]
Looks like we're going to go with rolling patterns for the background, which would potentially change on refresh. Also changing the box to white (maybe with drop shadow?) will be likely.

**Comment by jamieshepherd** [comment]
Current batch of 5 images, will add more as they come in.
