### ISSUE TITLE
Ability to hide navigation bar

### ISSUE THREAD

**Issue by jamieshepherd** [jamieshepherd/tygr#3]
Sometimes users will just want to work off a list of issues, so the ability to hide the navigation bar will be useful.

**Comment by tomstembridge** [comment]
Hello Jamie, How's about having the nav bar "shrink" down to it's mobile state on a mouse out of 5 to 10 seconds. Having the smaller bar visible will keep the desired effect of increasing space and and reducing screen content while not freaking out non-tech savvies that they've somehow destroyed the site.

**Comment by jamieshepherd** [comment]
Might have an even easier way of implementing this with the ability to save preferences (large or small nav) to session or even user state. Will think more.
