### ISSUE TITLE
Issue History comments

### ISSUE THREAD

**Issue by MattR88** [jamieshepherd/tygr#35]
On the ‘Issue History’ section of the Issue Details page, are all comments viewable to all users?
For example where dev/design add comments to issues, are these then viewable to the client? If so, would it be worth considering something along the lines of a private or internal comment feature?

**Comment by MattR88** [comment]
Additionally, I think it would be quite important to be able to open private, or non client facing issues where internal QA or feedback required some additional updates. I think this would help integrate the system fully into the working process if it was used to log all issues on a project, internal and external.

**Comment by jamieshepherd** [comment]
Internal comments are a good idea, something I'll probably implement and assign to this thread. As for the latter comment, you can currently set issues (and even whole projects) to "hidden from client" by checking a box on creation / update. Is this the type of feature you were looking for? (This also wouldn't be hard to implement for comments, which would address the former).

**Comment by MattR88** [comment]
Ah, ok, yes, being able to create 'hidden' or non client facing issues on a project solves that, probably would have been helpful if I clicked the 'Hidden from Client?' tick box to see what happens!
