### ISSUE TITLE
Email alerts

### ISSUE THREAD

**Issue by MattR88** [jamieshepherd/tygr#37]
Is there any way to set email notifications on projects or issues? This would definitely be needed, to know when to check on client feedback or when issues are resolved or assigned back.

**Comment by jamieshepherd** [comment]
This is a very good idea, but we'd have to be able to turn it off, or assign notifications to specific users perhaps. I think this is something I will look into implementing but will need some more feedback on how exactly to go about it. Would they be notified after every issue is created, and then further would they be notified after an issue status has changed? These are all possible, but we will want to reduce the amount of spam the system sends out when there are 100 clients with potentially thousands of issues. Interested to hear your thoughts.

**Comment by MattR88** [comment]
Yeah it would need to be quite flexible if introduced to prevent endless unnecessary emails being sent out. I think this is something that might need to wait until after an initial test to see where email notifications might be useful. I know that I keep an eye on my incoming emails a lot more than anything else, so for me, I'd rather have too many emails but know that clients have responded or provided feedback than try to remember to keep checking back on the site, which invariably I'd forget to do.
Perhaps alerts are something to put on the back burner for a minute until an initial test has been done on a real life client.

**Comment by jamieshepherd** [comment]
Sounds good, I'll leave the issue open and assign it to "future" (i.e. post-1.0.0), but it's relatively trivial to implement when we're happy with a solution.

**Comment by jamieshepherd** [comment]
Have set up a basic architecture for send emails out based on events, at the moment it will only do this for user creation, but as users begin to use the application we can see where these might be wanted / required. We'll log these as separate issues when they are required.
