### ISSUE TITLE
Improve the dashboard

### ISSUE THREAD

**Issue by jamieshepherd** [jamieshepherd/tygr#4]
Lots of things to happen to the dashboard, some interesting statistics, personalised to the user.

**Comment by jamieshepherd** [comment]
Suggestion of graph based upon issue priority, how many are high medium low. Bar chart perhaps.

**Comment by StephenHodge** [comment]
make this graph - http://puu.sh/fpPbj/a6f4e9ef65.png clickable to see what the issues were?

**Comment by jamieshepherd** [comment]
Jason had same thoughts, not supported with charts.js but will look into doing something like this. Might look around for different charting libraries.

**Comment by jamieshepherd** [comment]
Expect that this won't be completed in time for beta, have moved to 1.0.0 milestone. Still taking suggestions for improvements.
