### ISSUE TITLE
Select rank and client for user

### ISSUE THREAD

**Issue by jamieshepherd** [jamieshepherd/tygr#5]
Make it better than entering an integer into a text box. Radio buttons for rank, dropdown for client perhaps.

**Comment by jamieshepherd** [comment]
Ask rank is only 1,2,3 - this can be implemented as radio selections (Administrator, Employee, Client).

**Comment by zenduo** [comment]
What about sub contractors...? Or do you think the employee has the same levels of options.

**Comment by jamieshepherd** [comment]
Can you give an example? I feel like they wouldn't see any more or less than a client but difficult thinking of that use-case.

**Comment by zenduo** [comment]
Does an employee see all active projects? Or are employees assigned to individual projects?

**Comment by jamieshepherd** [comment]
Employee will see all clients and all projects, the only difference between employee (Sponge) will be they can't view user information besides their own, and they can't delete clients or projects (but can create both). Admins can delete clients, projects, and also create new users, edit/delete users, change their passwords etc.

I don't think we need to particularly limit employees to much more, if they want to view other projects they should be allowed to, they just can't do any of the heavy stuff.

**Comment by zenduo** [comment]
My point here is that a freelancer for example, we would want to limit them to only the projects that they are working on.

**Comment by jamieshepherd** [comment]
Yeah that's a fair point, will have a think about how this could be integrated with the current architecture. For the moment they could just be assigned to the client they're working on, assigning them to individual projects will be a (small) bit of extra work.

**Comment by jamieshepherd** [comment]
Still going to look into freelancer / subcontractors, might open a new issue for this.
