### ISSUE TITLE
Show user rank on users page

### ISSUE THREAD

**Issue by zenduo** [jamieshepherd/tygr#50]
Show what rank a user has on the following page:
http://tygr.jamie.sh/users

E.g.
- Super Admin
- Staff
- Admin

Good to have if fault finding or seeing why someone cant do something

**Comment by jamieshepherd** [comment]
Fixed with https://github.com/jamieshepherd/tygr/commit/24172d0e5cce2180fc7af3a6b3793bdaa130ea29
