### ISSUE TITLE
Browser stack testing

### ISSUE THREAD

**Issue by zenduo** [jamieshepherd/tygr#53]
You are going to hate me for this one but browser stack testing will be required. I can provide you with out account credentials for testing.

This full list of supported browsers will need adding to the Help section.

**Comment by jamieshepherd** [comment]
IE9 is pretty much fully supported, but SVG breaks below so will need to do image fallbacks. Despite losing some javascript functionality (and media queries, which mean under IE8 ish the sites lose responsiveness) it actually still works pretty well, and is completely useable as far back as IE6 - obviously with some visual artifacts.

**Comment by jamieshepherd** [comment]
Fixed SVG support at lunch. Will do a few more tests for compatability and likely be able to close this off.

**Comment by jamieshepherd** [comment]
IE6  works, and can be navigated, but is not pretty.
IE7  partly supported, with a few small glitches (no font-awesome icons for example).
IE8+ fully supported
Chrome + Firefox + Safari fully supported

Other browsers untested.
