### ISSUE TITLE
Redesign client projects list

### ISSUE THREAD

**Issue by jamieshepherd** [jamieshepherd/tygr#6]
It's not the most effective design right now, it could be made a lot warmer and with more useful information.

**Comment by StephenHodge** [comment]
An easy update would be to make the whole box a link to remove the 'view project' text... unless there can be other link texts just not in what I'm seeing here...

**Comment by jamieshepherd** [comment]
You're right, I think it needs a bit of a re-design in general, but making the whole box a link is a good stop-gap. :+1:

**Comment by jamieshepherd** [comment]
Pushing this to 1.0.0 as well.
